require "base64"

default_platform(:ios)

platform :ios do
  CERT_REPO_URL = "https://github.com/juntjtang18/LangGo-certificates.git"

  def match_git_auth
    Base64.strict_encode64("juntjtang18:#{ENV['MATCH_GIT_TOKEN']}")
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    match(
      type: "appstore",
      git_url: CERT_REPO_URL,
      git_basic_authorization: match_git_auth,
      readonly: true,
      api_key: api_key
    )

    build_app(
      scheme: "LangGo",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key
    )
  end
end