default_platform(:ios)

platform :ios do
  desc "Create App Store signing certs and profiles"
  lane :setup_signing do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    match(
      type: "appstore",
      api_key: api_key
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    match(
      type: "appstore",
      readonly: true,
      api_key: api_key
    )

    build_app(
      scheme: "LangGo",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key
    )
  end

desc "Delete old distribution signing from match"
lane :nuke_signing do
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY"]
  )

  match_nuke(
    type: "appstore",
    api_key: api_key
  )
end
end

